name: pneumonia-detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - torchvision
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - pillow
    - scikit-learn
    - seaborn
    - jupyter
    - opencv-python
